#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : metacity
Version  : 3.26.0
Release  : 7
URL      : https://download.gnome.org/sources/metacity/3.26/metacity-3.26.0.tar.xz
Source0  : https://download.gnome.org/sources/metacity/3.26/metacity-3.26.0.tar.xz
Summary  : Metacity library
Group    : Development/Tools
License  : GPL-2.0
Requires: metacity-bin
Requires: metacity-lib
Requires: metacity-data
Requires: metacity-locales
Requires: metacity-doc
BuildRequires : gettext
BuildRequires : libgtop-dev
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gsettings-desktop-schemas)
BuildRequires : pkgconfig(gthread-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(ice)
BuildRequires : pkgconfig(libcanberra-gtk3)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(sm)
BuildRequires : pkgconfig(xcursor)
BuildRequires : startup-notification-dev
BuildRequires : zenity

%description
Metacity is not a meta-City as in an urban center, but rather
Meta-ness as in the state of being meta. i.e. metacity : meta as
opacity : opaque. Also it may have something to do with the Meta key
on UNIX keyboards.

%package bin
Summary: bin components for the metacity package.
Group: Binaries
Requires: metacity-data

%description bin
bin components for the metacity package.


%package data
Summary: data components for the metacity package.
Group: Data

%description data
data components for the metacity package.


%package dev
Summary: dev components for the metacity package.
Group: Development
Requires: metacity-lib
Requires: metacity-bin
Requires: metacity-data
Provides: metacity-devel

%description dev
dev components for the metacity package.


%package doc
Summary: doc components for the metacity package.
Group: Documentation

%description doc
doc components for the metacity package.


%package lib
Summary: lib components for the metacity package.
Group: Libraries
Requires: metacity-data

%description lib
lib components for the metacity package.


%package locales
Summary: locales components for the metacity package.
Group: Default

%description locales
locales components for the metacity package.


%prep
%setup -q -n metacity-3.26.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1506984379
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-common -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FCFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-common -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-common -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export CXXFLAGS="$CXXFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-common -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1506984379
rm -rf %{buildroot}
%make_install
%find_lang metacity

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/metacity
/usr/bin/metacity-message
/usr/bin/metacity-theme-viewer
/usr/bin/metacity-window-demo

%files data
%defattr(-,root,root,-)
/usr/share/applications/metacity.desktop
/usr/share/glib-2.0/schemas/org.gnome.metacity.gschema.xml
/usr/share/glib-2.0/schemas/org.gnome.metacity.keybindings.gschema.xml
/usr/share/glib-2.0/schemas/org.gnome.metacity.theme.gschema.xml
/usr/share/gnome-control-center/keybindings/50-metacity-navigation.xml
/usr/share/gnome-control-center/keybindings/50-metacity-system.xml
/usr/share/gnome-control-center/keybindings/50-metacity-windows.xml
/usr/share/metacity/icons/metacity-window-demo.png

%files dev
%defattr(-,root,root,-)
/usr/include/metacity/libmetacity/meta-button.h
/usr/include/metacity/libmetacity/meta-color.h
/usr/include/metacity/libmetacity/meta-enum-types.h
/usr/include/metacity/libmetacity/meta-frame-borders.h
/usr/include/metacity/libmetacity/meta-frame-enums.h
/usr/include/metacity/libmetacity/meta-theme.h
/usr/lib64/libmetacity.so
/usr/lib64/pkgconfig/libmetacity.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libmetacity.so.1
/usr/lib64/libmetacity.so.1.1.0

%files locales -f metacity.lang
%defattr(-,root,root,-)

